blank_issues_enabled: false
contact_links:
  - name: ⚠ Feature request
    url: https://github.com/Tyrrrz/Gress/wiki/Maintenance-mode
    about: Sorry, but this project is in maintenance mode and no longer accepts new feature requests.
  - name: 📖 Wiki
    url: https://github.com/Tyrrrz/Gress/wiki
    about: Find usage guides and frequently asked questions.